config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'attachments#index'

  resources :attachments, only: %i[new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  scope :with_current_user, ->(user) { where(user: user).order(created_at: :desc) }

  has_one_attached :file
  belongs_to :user

  paginates_per 5
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attachments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @attachments = Attachment.with_current_user(current_user).page(params[:page])
  end

  def new
    @attachment = Attachment.new
  end

  def create
    @result = AttachmentCreateService.call(params, current_user)
    if @result[:success]
      flash.now[:notice] = 'File successfully zipped'
      render :password
    else
      flash.now[:alert] = @result[:alert]
      render :new, status: @result[:http_status]
    end
  end
end

app/views/attachments/index.html.haml
%table.table
  %thead
    %tr
      %th Creation date
      %th File name
      %th Size
      %th Link
  %tbody
    - @attachments.each do |attachment|
      %tr
        %td= attachment.created_at.to_date
        %td= attachment.name
        %td= Converter.new.convert(attachment.size)
        %td= link_to 'Download', attachment.file
= paginate @attachments

app/views/attachments/new.html.haml
%form{:action => "/attachments", :method => "post", :enctype => "multipart/form-data"}
  %input{:name => "authenticity_token", :type => "hidden", :value => form_authenticity_token()}/
  %label.font-weight-bold{:for => "zipname"} Enter zip filename (optional):
  %input.form-control{:name => "zip_name", :placeholder => "enter a name for the zip", :type => "text"}
  %p
  %label{:for => "files"} Select Multiple files:
  %input#files{:multiple => true, :name => "files[]", :type => "file"}/
  %button.btn.btn-primary{:type => "submit"} Submit

app/views/attachments/password.html.haml
Password:
= @result[:password]

app/views/layouts/_header.html.haml
%header.d-flex.flex-wrap.justify-content-center.py-3.mb-4.border-bottom
  = link_to root_path, class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" do
    %span.fs-4 Zipper
  - if current_user.nil?
    = link_to 'Sign in', new_user_session_path, class: 'nav-link'
    \ 
  - else
    = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'
    \ 
    = link_to "Change password", edit_user_registration_path, class: 'nav-link'
    \ 
  %ul.nav.nav-pills
    %li.nav-item
      = link_to 'File list', root_path, class: ['nav-link', ('active' if current_page?(root_path))]
    %li.nav-item
      = link_to 'Add files', new_attachment_path, class: ['nav-link', ('active' if current_page?(new_attachment_path))]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Zipper
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %main
      .container
        = render 'layouts/header'
        - if flash.alert
          - flash.each do |type, msg|
            .alert.alert-danger
              = msg
              %p
        - if flash.notice
          - flash.each do |type, msg|
            .notice.alert-success
              = msg
              %p
        = yield